version: "3.8"
services:
  api-postgres:
    image: postgres:15.3-alpine
    platform: linux/x86_64
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
    volumes:
      - ./data/postgres-data:/var/lib/postgresql/data

  api-pgadmin:
    image: dpage/pgadmin4:latest
    platform: linux/x86_64
    restart: always
    depends_on:
      - api-postgres
    environment:
      PGADMIN_DEFAULT_EMAIL: user@localhost.com
      PGADMIN_DEFAULT_PASSWORD: password
    ports:
      - 8080:80
    volumes:
      - ./data/pgadmin-data:/var/lib/pgadmin

networks:
  default:
    name: api-network
    external: true
